#!/usr/bin/env bash
# Integrate Jenkins build status with GitHub
# Have a look at https://docs.github.com/en/rest/commits/statuses for more.
# Interface:
#   $1: GIT_COMMIT : Git jenkins plugin commit environment variable
#   $2: ACCESS_TOKEN : GitHub access token environment variable
#   $3: BUILD_URL: Jenkins build URL environment variable
#   $4: STATE : success, failure, pending

REPOSITORY=$1
GIT_COMMIT=$2
ACCESS_TOKEN=$3
BUILD_URL=$4
STATE=$5

GH_URL="https://api.GitHub.com/repos/SquadroneSystem/$REPOSITORY/statuses/$GIT_COMMIT"
JENKINS_URL="${BUILD_URL}console"

curl "$GH_URL" \
  -H "Authorization: token $ACCESS_TOKEN" \
  -H "Content-Type: application/json" \
  -X POST \
  -d "{\"state\": \"$STATE\",\"context\": \"continuous-integration/jenkins\", \"description\": \"Jenkins\", \"target_url\": \"$JENKINS_URL\"}"